### ISSUE TITLE
MobileForAll entirely broken

### ISSUE THREAD

**Issue by Xoeq** [Mega-Mewthree/BetterDiscordPlugins#106]
It's meant to show other people that I'm on mobile, correct? It just doesn't work.

**Comment by Mega-Mewthree** [comment]
No, it's meant to allow you to see other people on mobile when they are on idle or do not disturb status.

**Comment by Illegal-Services** [comment]
MobileForAll is not working anymore, right?

**Comment by Ao1Pointblank** [comment]
it is entirely broken
