### ISSUE TITLE
Zere's Plugin Library

### ISSUE THREAD

**Issue by TheBitLlama** [Mega-Mewthree/BetterDiscordPlugins#12]
How can I install Zeres plugin lib?

**Comment by Lopass-Tenclea** [comment]
Search online
Won't be very hard to find
It work like a normal plugin

**Comment by TheBitLlama** [comment]
I found it on GitHub, but I dont know, which file may I use

**Comment by Lopass-Tenclea** [comment]
https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/ZeresPluginLibrary
Copy this and enable it like a regular plugin, hope this will help 😁
