### ISSUE TITLE
AutoStartRichPresence injection problem

### ISSUE THREAD

**Issue by AtomikHeh** [Mega-Mewthree/BetterDiscordPlugins#122]
So it seems like there's a problem going on with AutoStartRichPresence, whenever the Experimental: RPC Event Injection feature is enabled I'm getting an error saying "Failed to set Rich Presence activity." (as shown on the screenshot) From what I've seen I'm not the only one having this issue. No Idea what might be causing it but I'm leaving an issue report here since I've never experienced it before.
![image](https://user-images.githubusercontent.com/92219985/137585818-8f0ce98f-6d01-48d4-af71-98acb442d402.png)

**Comment by AtomikHeh** [comment]
Great, that worked perfectly. Thanks for the help !

**Comment by prinsecine** [comment]
> ![image](https://user-images.githubusercontent.com/36238069/137626641-1a809bee-8ebe-4c93-89c5-7bf71fa5178e.png) Go to the plugins tab ![image](https://user-images.githubusercontent.com/36238069/137626648-e6fb329a-d7b2-46e9-8143-82111278d18e.png) Click the Edit ![image](https://user-images.githubusercontent.com/36238069/137626689-ddf62dc9-6195-4ff0-b9b9-982778ca628e.png) Go to these lines and add that to it

when i tried ding it i got this 
![Screenshot 2022-01-10 214754](https://user-images.githubusercontent.com/97491641/148872271-75fc4368-2d9b-4400-b9a8-119752f11ffc.png)
