### ISSUE TITLE
[TeX] Attach not outputting formula [bug]

### ISSUE THREAD

**Issue by nathanwelsh8** [Mega-Mewthree/BetterDiscordPlugins#127]
I am unable to Attach any TeX formula into chat,
![image](https://user-images.githubusercontent.com/36056683/138325926-529159a8-45bd-4f75-a999-9b995f69df69.png)

I am on v1.0.0 and have ZeresPluginLibraryv1.2.32 installed and active.

**Comment by zwamdurkel** [comment]
Same issue.

<html>
<body>
<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">TeX.plugin.js:21560</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: ZeresPluginLibrary.ReactTools.getOwnerInstance(...).promptToUpload is not a function
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at TeX.attachImage (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">VM625 TeX.plugin.js:21560</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at onConfirm (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">VM625 TeX.plugin.js:21504</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | attachImage | @ | TeX.plugin.js:21560
-- | -- | -- | --
  | onConfirm | @ | TeX.plugin.js:21504
  | async function (async) |   |  
  | onConfirm | @ | TeX.plugin.js:21503
  | onClick | @ | 54f6a2f….js:3473
  | Ye | @ | 54f6a2f….js:5864
  | Xe | @ | 54f6a2f….js:5864
  | (anonymous) | @ | 54f6a2f….js:5884
  | Mr | @ | 54f6a2f….js:5884
  | Pr | @ | 54f6a2f….js:5884
  | (anonymous) | @ | 54f6a2f….js:5890
  | ke | @ | 54f6a2f….js:5972
  | (anonymous) | @ | 54f6a2f….js:5886
  | Vr | @ | 54f6a2f….js:5886
  | rn | @ | 54f6a2f….js:5873
  | nn | @ | 54f6a2f….js:5873
  | t.unstable_runWithPriority | @ | 54f6a2f….js:6194
  | Ki | @ | 54f6a2f….js:5895
  | we | @ | 54f6a2f….js:5972
  | en | @ | 54f6a2f….js:5872
  | r | @ | 9a05deb….js:126

</span></div>
</body>
</html>

**Comment by FlyingFaller** [comment]
same issue

**Comment by MSWS** [comment]
Can confirm. Unable to attach any images.

**Comment by Frontear** [comment]
Discord seems to have changed the property. I wish I was more knowledgeable in Plugins or Discord itself, but I am not, so sadly I can't help fix this. All I can say is that the querySelector node no longer has the function we desire.

**Comment by Frontear** [comment]
Upon experimenting for a long while, I found a fix. In the callback, navigate to lines 21560, and change the code from:
```javascript
ZeresPluginLibrary.ReactTools.getOwnerInstance(document.querySelector(':-webkit-any([class*=" uploadArea-"], [class^="uploadArea-"])')).promptToUpload(
    fileList,
    ZeresPluginLibrary.DiscordModules.SelectedChannelStore.getChannelId(),
    false,
    true
);
```
to:
```javascript
BdApi.findModuleByProps("promptToUpload").promptToUpload(
    fileList,
    ZeresPluginLibrary.ReactTools.getOwnerInstance(document.querySelector(':-webkit-any([class*=" uploadArea-"], [class^="uploadArea-"])')).props.channel,
    false,
    true
);
```

I'm not exactly experienced, so I have no idea if this fix will last. For the time being however, I got my functionality back. Hoping @Mega-Mewthree will see this and find a better implementation.

**Comment by Viibrant** [comment]
Bumping for more attention, @Frontear's answer fixed the functionality for me. pls fix

**Comment by FlyingFaller** [comment]
This does fix the issue!

**Comment by DovePod** [comment]
Thx @Frontear for, now, this works on my device!
@Mega-Mewthree, please do take a look at this.

**Comment by DindinYT37** [comment]
This doesn't fix it anymore, atleast for me.

**Comment by DovePod** [comment]
Yeah, same.

**Comment by Plutonium-239** [comment]
Yeah I think it broke again @Frontear is it still working for you ?(updated/most recent versions)

**Comment by Plutonium-239** [comment]
@Mega-Mewthree why'd you close it?
The last three replies were about the fix not working anymore

**Comment by DindinYT37** [comment]
> @Mega-Mewthree why'd you close it? The last three replies were about the fix not working anymore Also @Frontear can you confirm if this is still working?

Because it works again.

**Comment by Plutonium-239** [comment]
I didn't receive an update, I'm still on v1.0.0 but latest commit is 1.0.1
Does it not automatically check for updates through better discord? [other plugins do]

**Comment by DindinYT37** [comment]
> I didn't receive an update, I'm still on v1.0.0 but latest commit is 1.0.1 Does it not automatically check for updates through better discord? [other plugins do]
I have it installed via the Plugin Repository so it notifies me of updates, update 1.0.1 is available and works though.

**Comment by DovePod** [comment]
I'm using 4abf825ea08c91746f3250cef8e2b1219824bf56, and It's all working.
