### ISSUE TITLE
Cant select "Active Profile" and "Select Profile To Edit" after the latest BDFDB [BUG] [AutoStartRichPresence]

### ISSUE THREAD

**Issue by WatanabeDaiki135** [Mega-Mewthree/BetterDiscordPlugins#130]
![Screenshot 2021-10-30 033208](https://user-images.githubusercontent.com/87174986/139529381-db4241dc-75df-4931-84c0-f0a979a454dc.png)

**Comment by WatanabeDaiki135** [comment]
Even if we click the dropdown menu, its still blank and no dropdown menu will show

**Comment by goaliefox07** [comment]
having this issue as well, have no idea how to fix it

**Comment by Bensus86** [comment]
Same here, waiting for a fix. Thanks!

**Comment by Bensus86** [comment]
Same here, waiting for a fix. Thanks!
@Mega-Mewthree  little help please ouo (Mago Berry)

**Comment by jubewe** [comment]
Same, its since the new discord updates...

**Comment by Veyral** [comment]
Having this issues as well, waiting for a fix.
Big thanks!

**Comment by zaquanza** [comment]
Also having this issue, hope it gets fixed soon

**Comment by Luki20091** [comment]
Same! waiting for a fix this.

**Comment by dark-fedora** [comment]
have been waiting on a fix for this for a few days, hope that one is in progress <3

**Comment by AlexanderHOtt** [comment]
Same issue

**Comment by YOTYTeaM** [comment]
Same issue
can someone give me AutoStartRichPresence.config.json

 'C:\Users\<user>\AppData\Roaming\BetterDiscord\plugins\AutoStartRichPresence.config.json'

for choice Active Profile

**Comment by Xzer0o0** [comment]
same here

**Comment by gabitoesbobo** [comment]
bump, having this issue too

**Comment by circle67** [comment]
@YOTYTeaM here is my config file minus the profiles:
```
{
    "settings": {
        "lastChangelogVersionSeen": "2.0.4",
	"activeProfileID": 0
    },
    "profiles": [
        {
            "name": "Your profiles should be here."
        }
    ]
}
```

All you need to change/add is `"activeProfileID": {an integer}`

**Comment by RkPereiraa16** [comment]
New updates about this?

**Comment by BrownieBROF** [comment]
someone has any clue of what to do?

**Comment by unholfretka2137** [comment]
When fix?

**Comment by 19216800** [comment]
Hello?

**Comment by Luo-jaiwen** [comment]
一样

**Comment by JustAryamaan** [comment]
Same problem.. I'll use vscode to do the richpresence then.

**Comment by RkPereiraa16** [comment]
I read and saw about everything the repositories contained and etc and still I can't fix this bug, has anyone managed to?

**Comment by WatanabeDaiki135** [comment]
nope, still broken for me :<

**Comment by WatanabeDaiki135** [comment]
Well after the last update of this plugin, now everything works fine now, thanks to the developer for fixing this issue.

I'm going to close this now, and have a good day ^-^)/
