### ISSUE TITLE
Unable to edit Rich Presence in discord or in config,

### ISSUE THREAD

**Issue by Lootboxess** [Mega-Mewthree/BetterDiscordPlugins#18]
The settings for AutoStartRichPresence do not show when clicking settings for the plugin as seen here https://gyazo.com/d815b7d1d772d4c72670ac91005d9486. I am also unable to edit the config to change the settings as it just keeps the old settings I had. Deleting the config and reloading the plugin also does nothing.

**Comment by Mega-Mewthree** [comment]
Reinstall [ZeresPluginLibrary](https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js).
