### ISSUE TITLE
NoDeleteMessage 

### ISSUE THREAD

**Issue by blosomKitty** [Mega-Mewthree/BetterDiscordPlugins#24]
the plugin suddenly stopped. when someone deletes on discord it completely deletes it without showing it was ever there

**Comment by yorik100** [comment]
It's broken, can confirm

**Comment by threelol** [comment]
it's weird because, it works for some people and not for others

**Comment by blosomKitty** [comment]
seems like the problem is the discord update. could be something else though

**Comment by Mega-Mewthree** [comment]
Fixed in #26, please manually update.
