### ISSUE TITLE
NoDeleteMessage

### ISSUE THREAD

**Issue by threelol** [Mega-Mewthree/BetterDiscordPlugins#25]
Plugin has stopped working for me, not sure why - works for others and when I try to restart it gives me this error
![image](https://user-images.githubusercontent.com/48558472/56811080-d6529a00-682f-11e9-8d56-d434b483b548.png)

**Comment by Pointless-simulation** [comment]
Same for me -- Stopped working after the discord update.

**Comment by Mega-Mewthree** [comment]
Fixed in #26.

**Comment by Mega-Mewthree** [comment]
You will need to manually update.
