### ISSUE TITLE
Some messages still get deleted after a few hours

### ISSUE THREAD

**Issue by xFahrenheightx** [Mega-Mewthree/BetterDiscordPlugins#32]
Not sure what's causing it either, but deleted chats were entirely deleted after a few hours outside of my control. Nodeletemessages plugin seems to failing.

**Comment by Mega-Mewthree** [comment]
It only prevents the client from removing deleted messages from internal stores when receiving a MESSAGE_DELETE event. It does not prevent Discord from freeing old data in stores.
