### ISSUE TITLE
Cannot find ZeresPluginLibrary

### ISSUE THREAD

**Issue by TangoTangoX** [Mega-Mewthree/BetterDiscordPlugins#35]
Hello, Rich Presence requires Zeres but I cannot seem to find it, if anyone could link a download it'd be greatly appreciated! Thank you
![image](https://user-images.githubusercontent.com/51096684/58913989-6f0bed80-86eb-11e9-8967-924cd5285403.png)
![image](https://user-images.githubusercontent.com/51096684/58913999-759a6500-86eb-11e9-9829-e2796835c529.png)

**Comment by Mega-Mewthree** [comment]
https://betterdiscord.net/ghdl?id=2252
