### ISSUE TITLE
Issue with edits on NoDeleteMessage

### ISSUE THREAD

**Issue by Lootboxess** [Mega-Mewthree/BetterDiscordPlugins#36]
When someone edits, it will no longer show the previous edit or show the new edit. https://gyazo.com/6839652f370b9fdb105df93456dfa21d

**Comment by zxFirefly** [comment]
I've also been having this issue for about a week

**Comment by xavkno** [comment]
also having this problem unfortunately

**Comment by Lootboxess** [comment]
Can we get an update on this? Its been a few weeks now with this problem.

**Comment by RefexHD** [comment]
It looks like he will publish newer version here now: https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/blob/master/NoDeleteMessages/
