### ISSUE TITLE
[NoDeleteMessages] Fix meta

### ISSUE THREAD

**Issue by KaKi87** [Mega-Mewthree/BetterDiscordPlugins#38]
https://github.com/Mega-Mewthree/BetterDiscordPlugins/blob/master/Plugins/NoDeleteMessages/NoDeleteMessages.plugin.js#L1

NoDeleteMessages's meta is actually AutoStartRichPresence's meta.

**Comment by Mega-Mewthree** [comment]
NAB; this is intentional to bypass a certain theme dev's ban on this plugin.

**Comment by KaKi87** [comment]
Lol I know who that is xD
