### ISSUE TITLE
AutoStartRichPresence client ID authentication failed.

### ISSUE THREAD

**Issue by TheUnkn0wnN00b** [Mega-Mewthree/BetterDiscordPlugins#40]
When I try to start the plugin it starts and about 10-15 seconds later it spits out the error, "Rich Presence client ID authentication failed. Make sure your client ID is correct." The client ID in the settings is identical to the one in the Discord developer portal.

**Comment by Mega-Mewthree** [comment]
Have you followed the troubleshooting guide?
