### ISSUE TITLE
AutoStartRichPresence injected on Stable, not on PTB

### ISSUE THREAD

**Issue by Guest173661** [Mega-Mewthree/BetterDiscordPlugins#42]
I use 2 accounts at once, My alt being on PTB and my main being on Stable.
I want to use a different RP (external application) for my Main, and another one (plugin) on my Alt, Problem is that using the plugin on the PTB client doesn't appear [picture 1], and once I close the external application for my main, the plugin injects the RP on Stable even when Stable doesn't have BD [picture 2]
![image](https://user-images.githubusercontent.com/29669519/60482864-c5a62080-9cc5-11e9-9842-b512cd6ba070.png)

![image](https://user-images.githubusercontent.com/29669519/60483063-7d3b3280-9cc6-11e9-8103-f75669f2af56.png)

**Comment by Mega-Mewthree** [comment]
Try enabling the experimental switch in the plugin's settings.

**Comment by Guest173661** [comment]
That fixed it! Thanks! Closing issue now.
