### ISSUE TITLE
[Help] Entering A Game Doesn't Switch To That Rich Presence

### ISSUE THREAD

**Issue by grravity** [Mega-Mewthree/BetterDiscordPlugins#47]
With the 'Autostart Rich Presence' plugin, how can I make it so when I enter a game, spotify, or any other program, it switches the Rich Presence to that and off my meme one, then when I exit it, it goes back?  It seems to just stay stuck on the meme one.

(Note I tested this with a few games that normally work, before I enabled Auto Start Rich Presence, as well as Spotify.)

**Comment by Z3ROGRAV1TYx** [comment]
Still unable to figure this out.

**Comment by ocr893sa** [comment]
i would like to know this too
