### ISSUE TITLE
 In the new version of discord isn't working

### ISSUE THREAD

**Issue by Patdjorge** [Mega-Mewthree/BetterDiscordPlugins#51]
This plugin has a problem, in the new version of discord, the plugin does not work in its settings, fix it. Without settings there is no Rich Presence.

![sa](https://user-images.githubusercontent.com/55152810/64631613-5f3d2d00-d3ef-11e9-912c-e04615c467ed.png)

OBS: I have ZeresPluginLibrary, and in the old version of discord RichPresence is working perfectly

**Comment by azerhero** [comment]
i had the same issue, please fix this

thank you
