### ISSUE TITLE
[NoDeleteMessages] Feature request/Question — Show deleted messages as a different color.

### ISSUE THREAD

**Issue by VizzraN** [Mega-Mewthree/BetterDiscordPlugins#52]
I just got BetterDiscord and NoDeletedMessages and was wondering if there was a way to make it so that the deleted messages would appear a different color such as red so i know not to mention anything about the message. I briefly looked at the js file but i really have no idea what i would be looking for to be able to do this. If it can be done could someone let me know what i should edit and if its not possible do you think this could be added in the future?

**Comment by Evernow** [comment]
This was a feature indeed, but the issue is the update broke it, wait for it to be updated :D
