### ISSUE TITLE
AutoStartRichPresence v1.1.0 doesn't work.

### ISSUE THREAD

**Issue by YUleH4xx0r** [Mega-Mewthree/BetterDiscordPlugins#53]
AutoStartRichPresence dosen't work after the latest discord uptade , When you click in settings we only see Enable Start Time and Experimental: RPC Event Injection (You can see it in the screen) so yeah.

Sorry for my horrible english i'm baguette.)
![Capture d’écran (35)](https://user-images.githubusercontent.com/55235546/64774739-11dad000-d555-11e9-9d64-3f05b37e13b2.png)

**Comment by Kashotex** [comment]
Yeah same. It probably broke with the light theme update like Metalloriff's plugins

**Comment by JoTiiK** [comment]
Same for me 
![image](https://user-images.githubusercontent.com/42248508/64925686-c8a8ab80-d7f4-11e9-9535-d6ed20433f49.png)

**Comment by Lisinsin** [comment]
Same problem
![screen](https://user-images.githubusercontent.com/35670224/64962306-d6ffd180-d89f-11e9-810f-40cc67eed79b.PNG)

**Comment by neroxqq** [comment]
Discord is starting to be like Valve. Every update itself fucks something.

**Comment by arefiq09** [comment]
This issue was actually caused by another plugin. Mine caused by ZeresPluginLibrary v1.2.7 by Zerebos. That plugin update has since fixed the settings for this plugin as well.

**Comment by JoTiiK** [comment]
same as arefiq09

**Comment by derMiepz** [comment]
> This issue was actually caused by another plugin. Mine caused by ZeresPluginLibrary v1.2.7 by Zerebos. That plugin update has since fixed the settings for this plugin as well.

So what exactly do I have to do? ZeresPluginLibrary doesn't have an update, neither does this one. Disabling ZeresPluginLibrary didn't fix it.
