### ISSUE TITLE
[MobileForAll] mini bug with Profile Pictures.

### ISSUE THREAD

**Issue by Strencher** [Mega-Mewthree/BetterDiscordPlugins#55]
![image](https://user-images.githubusercontent.com/46447572/72730523-d189ff00-3b91-11ea-9ec1-e005bff66b6c.png)

- Discord Canary **version** 52909

**Comment by Mega-Mewthree** [comment]
Fixed with https://github.com/Mega-Mewthree/BetterDiscordPlugins/commit/18a359bdad2398c3bdd51c947647afe42a721ca0.
