### ISSUE TITLE
[MobileForAll] Typing Indicator messes up the phone icon.

### ISSUE THREAD

**Issue by ReallPanda** [Mega-Mewthree/BetterDiscordPlugins#56]
After the user with the icon is done typing the icon goes into an oval shape and not the new phone icon. [When the user is typing](https://imgur.com/a/7Lc8fmo). [When user is done typing](https://imgur.com/a/4yvmw2c). If you need more info just ask.

**Comment by Mega-Mewthree** [comment]
Fixed with https://github.com/Mega-Mewthree/BetterDiscordPlugins/commit/18a359bdad2398c3bdd51c947647afe42a721ca0.
