### ISSUE TITLE
RightClickRoleForID no longer starts up

### ISSUE THREAD

**Issue by silent** [Mega-Mewthree/BetterDiscordPlugins#7]
RightClickRoleForID doesn't start up.
![image](https://user-images.githubusercontent.com/36117192/51573393-c01ef180-1e6e-11e9-920b-63554a29f880.png)

**Comment by KarlOfDuty** [comment]
Same here.

**Comment by TheDarkBomber** [comment]
Same. @Mega-Mewthree Please fix this issue

**Comment by Puyodead1** [comment]
Same, its all of @Lucario 🌌 V5.0.0#7902 plugins. PLEASE, these are all great plugins!

**Comment by lucario** [comment]
Hello 👀

**Comment by Vastrix** [comment]
Indeed :/

**Comment by Mega-Mewthree** [comment]
This plugin is now deprecated.
