### ISSUE TITLE
[DiscordCakeDay] Will not start after being disabled.

### ISSUE THREAD

**Issue by snappyapple632** [Mega-Mewthree/BetterDiscordPlugins#8]
Current version: 0.1.3

Expected behavior: The plugin should start up on demand without errors.

Actual behavior: On the first startup upon starting Discord, the plugin will boot the first time, but subsequent attempts will result in an error stating the plugin could not be loaded.

How to reproduce: 1) Start Discord with the latest version of BandagedBetterDiscord installed and have DiscordCakeDay loaded but not enabled. 2) Enable the program. It should start up without problems. 3) Disable the program, then enable it again. It should result in an error stating the plugin could not be loaded.

**Comment by Lopass-Tenclea** [comment]
Just leave it enabled :|

**Comment by Favna** [comment]
Bumping since it's still not fixed. The above is obviously not a solution as when it's involuntarily disabled (i.e. BD reinstalled) it cannot be re-enabled.

**Comment by Mega-Mewthree** [comment]
Should have been fixed.
