### ISSUE TITLE
Problems with buttons

### ISSUE THREAD

**Issue by BfGanimeshnik** [Mega-Mewthree/BetterDiscordPlugins#82]
Hi, I have a problem with buttons, I provide a title and a link for it, but nothing happens when clicked.
![image](https://user-images.githubusercontent.com/55851088/106298483-fe70f780-6264-11eb-9975-71311473d601.png)

**Comment by AkaFarukon** [comment]
This is still a current issue with me as well :)

**Comment by SuperSweatyTejas** [comment]
same here

**Comment by Vyxxxx** [comment]
Same for me too!

**Comment by BfGanimeshnik** [comment]
It turns out that there is no problem, the buttons work, but I just myself cannot navigate through them, while other people can
